// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXBtfiEDR_8tnhAo_GiUeHWgQhZx9TXY0',
    appId: '1:327943554146:web:189a0761a5c6d9e29c3d3b',
    messagingSenderId: '327943554146',
    projectId: 'manage-school-b9e0c',
    authDomain: 'manage-school-b9e0c.firebaseapp.com',
    storageBucket: 'manage-school-b9e0c.firebasestorage.app',
    measurementId: 'G-6Q5PCK8C4P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxGaaaX9Om9CTMbTt1lVh9dPDFXt5Yb0s',
    appId: '1:327943554146:android:161a66667c99e6d49c3d3b',
    messagingSenderId: '327943554146',
    projectId: 'manage-school-b9e0c',
    storageBucket: 'manage-school-b9e0c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkR67_tt3sSGcmDAR8WjLRKqm-RIycWck',
    appId: '1:327943554146:ios:e3fed2bfcebf354f9c3d3b',
    messagingSenderId: '327943554146',
    projectId: 'manage-school-b9e0c',
    storageBucket: 'manage-school-b9e0c.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkR67_tt3sSGcmDAR8WjLRKqm-RIycWck',
    appId: '1:327943554146:ios:e3fed2bfcebf354f9c3d3b',
    messagingSenderId: '327943554146',
    projectId: 'manage-school-b9e0c',
    storageBucket: 'manage-school-b9e0c.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXBtfiEDR_8tnhAo_GiUeHWgQhZx9TXY0',
    appId: '1:327943554146:web:06bbdffa11a3adfe9c3d3b',
    messagingSenderId: '327943554146',
    projectId: 'manage-school-b9e0c',
    authDomain: 'manage-school-b9e0c.firebaseapp.com',
    storageBucket: 'manage-school-b9e0c.firebasestorage.app',
    measurementId: 'G-Y7TQFPFCHZ',
  );

}